[package]
name = "slog-json"
version = "2.0.3-pre"
authors = ["Dawid Ciężarkiewicz <dpc@dpc.pw>"]
description = "JSON drain for slog-rs"
keywords = ["slog", "logging", "json"]
license = "MPL-2.0"
documentation = "https://docs.rs/slog-json"
homepage = "https://github.com/slog-rs/slog"
repository = "https://github.com/slog-rs/json"
readme = "README.md"

[lib]
path = "lib.rs"

[features]
# Can't use "serde" as a fature name because we already depend on serde below.
nested-values = ["erased-serde"]
default = ["nested-values"]

[dependencies]
# slog = "2"
slog = { git = "https://github.com/slog-rs/slog", branch = "master", features = ["serde"]}
serde_json = "1"
serde = "1"
chrono = "0.4"

[dev-dependencies]
slog-async = "2"
erased-serde = {version = "0.3", optional = true }
